# This is a config for E2B sandbox template.
# You can use template ID (8zr0kth5jzu5pdfq9afh) or template name (gitwit-php) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("gitwit-php") # Sync sandbox
# sandbox = await AsyncSandbox.create("gitwit-php") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('gitwit-php')

team_id = "34eab90a-97dc-4be5-87e3-a17b6e6e8bc6"
dockerfile = "e2b.Dockerfile"
template_name = "gitwit-php"
template_id = " " 
